package guiproject;

import javax.swing.JOptionPane;

public class Register extends javax.swing.JFrame {

    
    public static String nama;
    public static String username;
    public static String password;   
    
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jNama = new javax.swing.JTextField();
        Username1 = new javax.swing.JTextField();
        NoHP = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButtonSubmit = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        Alamat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(192, 159, 128));
        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(86, 86, 86));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Silahkan masukkan data anda pada form dibawah ini");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 80, 310, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(86, 86, 86));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register Member");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 210, 30);

        jLabel3.setForeground(new java.awt.Color(86, 86, 86));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sebelum anda melakukan transaksi anda harus mempunyai akun");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(5, 65, 390, 14);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 100));

        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nama");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(67, 15, 30, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Username");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(67, 108, 54, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Password");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(67, 139, 51, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Ketik ulang Password");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(67, 170, 115, 15);
        jPanel2.add(jNama);
        jNama.setBounds(210, 12, 144, 22);

        Username1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(Username1);
        Username1.setBounds(210, 106, 144, 22);

        NoHP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NoHPKeyTyped(evt);
            }
        });
        jPanel2.add(NoHP);
        NoHP.setBounds(210, 44, 144, 22);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(210, 137, 145, 22);

        jPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jPasswordField2);
        jPasswordField2.setBounds(210, 168, 144, 22);

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSubmit);
        jButtonSubmit.setBounds(160, 200, 80, 23);

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Dengan membuat akun, anda menyetujui persyaratan dan persetujuan kami ");
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(15, 225, 370, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Alamat");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(67, 77, 110, 15);
        jPanel2.add(Alamat);
        Alamat.setBounds(210, 75, 144, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("No HP");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(67, 46, 110, 15);

        jButton1.setText("<=");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 200, 49, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Pictures\\Background\\mountains-1412683__340.png")); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(-130, 0, 540, 260);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 400, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here: 
       
        if(jNama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon untuk mengisi nama anda");
        }
        else if(NoHP.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon untuk mengisi nomor hp anda");
        }
        else if(Alamat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon untuk mengisi alamat anda");
        }
        else if(jPasswordField1.getText().equals(jPasswordField2.getText())){
            nama = jNama.getText();
            username = Username1.getText();
            password = jPasswordField1.getText();
            NoHP.getText();
            Alamat.getText();
            
            
            Login lg = new Login();
            lg.setTitle("Adventure Shop");
            lg.setLocationRelativeTo(null);
            lg.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
            lg.setVisible (true);
            dispose();
        }
        else if(!jPasswordField1.getText().equals(jPasswordField2.getText())){
            JOptionPane.showMessageDialog(null, "Mohon untuk menulis password yang sama");
        }
        
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void NoHPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoHPKeyTyped
        // TODO add your handling code here:
        char h = evt.getKeyChar();
        if(!(Character.isDigit(h))){
            evt.consume();
        }
    }//GEN-LAST:event_NoHPKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setTitle("Adventure Shop");
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
        lg.setVisible(true);
        dispose();      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Alamat;
    public static javax.swing.JTextField NoHP;
    private javax.swing.JTextField Username1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    // End of variables declaration//GEN-END:variables
}
